### PR TITLE
Switch away from gogo/status

### LINKED ISSUE #12: Investigate whether gogo/googleapis types implementing MessageName work with grpc/status
Following from the discussion in #9, it may be possible to use grpc/status instead of gogo/status when types implement `MessageName() string`.

### PR DESCRIPTION
**Pull request by johanbrandhorst**
Ridicolously enough, this now works :nerd_face:.

Fixes #12

### CODE REVIEW

**Comment by awalterschulze** [comment]
wat! really?

So we can even delete the gogo/status package?

**Comment by johanbrandhorst** [comment]
As far as I can tell... But the gogo/status package is still necessary if you're working with types that don't define `XXX_MessageName` or use `goproto_registration`. That's probably a very narrow use case.

**Comment by awalterschulze** [comment]
Should the example.proto maybe then include?

```proto
option (gogoproto.messagename_all) = true;
```

**Comment by johanbrandhorst** [comment]
Good idea. I briefly played around with removing `goproto_registration` but it's still necessary because grpc-gateway calls to `proto.EnumValueMap` when resolving query parameters:

https://github.com/grpc-ecosystem/grpc-gateway/blob/261dafe7abb6a223549d14d02faccffea736b7e8/runtime/query.go

**Comment by johanbrandhorst** [comment]
Bump :(?

**Comment by awalterschulze** [comment]
Interesting.  I replied via email a day ago, but it didn't seem to arrive as a comment here. Sorry.

**Review by awalterschulze — APPROVED** [review]

**Comment by awalterschulze** [comment]
Good to know about `proto.EnumValueMap`.  Very interesting.

**Pull request merged**
