### PR TITLE
Add example of using FieldMask

### LINKED ISSUE #9: Create new method with the FieldMask WKT
Need to find how to work around https://github.com/grpc-ecosystem/grpc-gateway/blob/58f78b988bc393694cef62b92c5cde77e4742ff5/runtime/query.go#L275 in gRPC-Gateway.

### PR DESCRIPTION
**Pull request by johanbrandhorst**
Add an example of using the FieldMask WKT type.

Fixes #9

### CODE REVIEW

**Comment by johanbrandhorst** [comment]
Outstanding work:

- Figure out why it outputs errors:
    ```
    proto: no encoder for wall uint64 [GetProperties]
    proto: no encoder for ext int64 [GetProperties]
    proto: no encoder for loc *time.Location [GetProperties]
    ```
- Properly implement XXX_MessageName on WKTs.

**Comment by awalterschulze** [comment]
@johanbrandhorst this is great news :)

@abursavich any update on moving github.com/abursavich/gogomarshal to github.com/gogo/gateway ?

**Comment by johanbrandhorst** [comment]
Add me as a collaborator on that repo please, I'll port abursavich's work over. It's almost verbatim from gateway so I assume he won't think I'm stealing his work.

**Comment by awalterschulze** [comment]
@johanbrandhorst Cool thanks :)  I made you an admin of the repo.

**Comment by johanbrandhorst** [comment]
Just need to add some tests before we can merge this.

**Comment by johanbrandhorst** [comment]
Added some tests, ready for another review now. @timonwong anything you think I should add to this example?

**Review by awalterschulze — APPROVED** [review]
so cool.  Thank you :)

**Pull request merged**
